name = "y-server"
main = "src/index.ts"
compatibility_date = "2024-02-22"

[[r2_buckets]]
binding = "CDN_BUCKET"
bucket_name = "cdn-yovy-app"

[dev]
port = 8788
ip = "localhost"
local_protocol = "http"
